chat/urls.py
from django.urls import path
from chat.views import message_view,message_to_user,delete_message

app_name = "chat"
urlpatterns = [
    path('messages/',message_view,name="messages"),
    path('messages/<str:username>/',message_to_user,name="message_user"),
    path('delete-message/',delete_message,name="delete_message"),
]

twitter/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls', namespace='post')),
    path('user/',include('useraccount.urls',namespace='user')),
    path('chat/',include('chat.urls',namespace='chat')),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

useraccount/urls.py
from django.urls import path
from useraccount.views import user_login,user_logout,UserLoginView,SignupView,profile_view,profile_update_view

app_name='user'
urlpatterns = [
    path('login/',user_login,name="login"),
    path('logout/',user_logout,name='logout'),
    path('register/',SignupView.as_view(),name='register'),
    path('profile/<str:username>/',profile_view, name='profile'),
    path('profile-edit/',profile_update_view,name="profile_update"),
]

useraccount/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"
        
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    contact = models.CharField(max_length=255, blank = True, null = True)
    address = models.CharField(max_length=255, blank = True, null = True)
    avatar = models.ImageField(upload_to="profile", blank = True, null = True)
    bio = models.TextField(blank=True,null = True)
    
    def __str__(self):
        return str(self.user)

useraccount/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from useraccount.models import Profile
from django import forms

User = get_user_model()

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username","password1","password2")
        
class ProfileForm(forms.ModelForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()
    class Meta:
        model = Profile
        fields = ("first_name","last_name","email","contact","address","avatar","bio")

useraccount/views.py
from django.shortcuts import render,reverse,get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.views.generic import CreateView
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView 
from useraccount.forms import SignUpForm,ProfileForm
from useraccount.models import Profile

User = get_user_model()

def user_login(request):
    form = AuthenticationForm(request.POST or None)
    if request.method == 'POST':
        username= request.POST.get('username')
        password= request.POST.get('password')
        user = authenticate(request,username=username, password=password)
        if user:
            login(request,user)
            return HttpResponseRedirect(reverse('post:home'))
        else:
            messages.add_message(request,messages.ERROR, 'invalid username or password')
            return HttpResponseRedirect(reverse('user:login'))
    context = {'form':form}
    return render(request,'login.html',context)

class UserLoginView(LoginView):
    template_name = 'login.html'
    
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('user:login'))

class SignupView(CreateView):
    template_name = "register.html"
    form_class = SignUpForm
    model = User
    success_url = reverse_lazy('user:login')
    
    def form_valid(self,form):
        user = form.save()
        Profile.objects.create(user=user)
        return super().form_valid(form)
    
def profile_view(request,username):
    user = get_object_or_404(User,username=username)
    form = None
    if request.user.is_authenticated and request.user.username == username:
        user = request.user
        initial_data = {
            'first_name':user.first_name,
            'last_name':user.last_name,
            'email':user.email,
            }
        form = ProfileForm(instance=user.profile,initial=initial_data)
    context = {'user':user,'form':form}
    return render(request,'profile.html',context)

@login_required
def profile_update_view(request):
    form = ProfileForm(request.POST or None, request.FILES or None,instance=request.user.profile)
    if form.is_valid():
        user = request.user
        user.first_name = form.cleaned_data.get("first_name")
        user.last_name = form.cleaned_data.get("last_name")
        user.email = form.cleaned_data.get("email")
        user.save()
        form.save()
        messages.add_message(request, messages.SUCCESS, 'your profile has been updated')
        return HttpResponseRedirect(reverse("user:profile",args=(request.user.username,)))
    context = {'form':form}
    return render(request,"profile.html",context)

useraccount/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="row mt-3">
    <div class="col-sm-12 col-md-3 col-lg-3"></div>
    <div class="col-sm-12 col-md-4 col-lg-4">
        <div class="card">
            <div class="card-header">
                <h2>Log In</h2>
            </div>
            <div class="card-body">
                {% if messages %}
                    {% for message in messages %}
                        <div class="text text-danger">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="Log In" class="btn btn-primary"/>
                </form>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-3 col-lg-3"></div>
</div>

{% endblock content %}

useraccount/templates/profile.html
{% extends 'base.html' %}

{% block content %}
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-success">
        {{message}}
    </div>
    {% endfor %}
{% endif %}
{% if form %}
<div>
    <form method="post" action="{% url 'user:profile_update' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" name="submit" class="btn btn-info"/>
    </form>
</div>
{% else %}
<div class="row">
    <div class="col-sm-12 col-md-4 col-lg-4"></div>
    <div class="col-sm-12 col-md-4 col-lg-4">
        {% if user.profile.avatar %}
        <div>
            <img class="img-fluid" src="{{ user.profile.avatar.url }}" alt=""/>
        </div>
        {% endif %}
    </div>
    <div class="col-sm-12 col-md-4 col-lg-4"></div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-2 col-lg-2"></div>
    <div class="col-sm-12 col-md-8 col-lg-8 ">
        <table class="table table-striped">
            <thead>
            <tbody class="fw-bold">
                <tr>
                    <td class="text-success">First Name:</td> <td>{{ user.first_name }}</td>
                </tr>
                <tr>
                    <td class="text-success">Last Name:</td> <td>{{ user.last_name }}</td>
                </tr>
                <tr>
                    <td class="text-success">Email:</td> <td>{{ user.email }}</td>
                </tr>
            </tbody>
        </thead>
        </table>
    </div>
    <div class="col-sm-12 col-md-2 col-lg-2"></div>
</div>
<div>
    {{form.as_p }}
</div>
{% endif %}
{% endblock content %}

useraccount/templates/register.html
{% extends 'base.html' %}
{% block content %}
<div class="row mt-3">
    <div class="col-sm-12 col-md-3 col-lg-3"></div>
    <div class="col-sm-12 col-md-4 col-lg-4">
        <div class="card">
            <div class="card-header">
                <h2>Log In</h2>
            </div>
            <div class="card-body">
                {% if messages %}
                    {% for message in messages %}
                        <div class="text text-danger">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="Sign up" class="btn btn-primary"/>
                </form>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-3 col-lg-3"></div>
</div>

{% endblock content %}