chat/urls.py
from django.urls import path
from chat.views import message_view,message_to_user,delete_message

app_name = "chat"
urlpatterns = [
    path('messages/',message_view,name="messages"),
    path('messages/<str:username>/',message_to_user,name="message_user"),
    path('delete-message/',delete_message,name="delete_message"),
]

post/urls.py
from django.urls import path
from post.views import home,create_post,edit_post,delete_post,comment_post,like_post

app_name = 'post'
urlpatterns = [
    path('',home,name='home'),
    path('create-post/',create_post,name="create_post"),
    path('edit-post/<int:postid>/',edit_post,name="edit_post"),
    path('delete-post/',delete_post,name='delete_post'),
    path('like-post/<int:postid>/',like_post,name="like_post"),
    path('comment-post/<int:postid>/',comment_post,name="comment_post"),
]

twitter/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls', namespace='post')),
    path('user/',include('useraccount.urls',namespace='user')),
    path('chat/',include('chat.urls',namespace='chat')),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

useraccount/urls.py
from django.urls import path
from useraccount.views import user_login,user_logout,UserLoginView,SignupView,profile_view,profile_update_view

app_name='user'
urlpatterns = [
    path('login/',user_login,name="login"),
    path('logout/',user_logout,name='logout'),
    path('register/',SignupView.as_view(),name='register'),
    path('profile/<str:username>/',profile_view, name='profile'),
    path('profile-edit/',profile_update_view,name="profile_update"),
]

post/models.py
from django.db import models
from django.conf import settings

class Status(models.TextChoices):
    DRAFT  = 'draft','DRAFT',
    PUBLIC = 'public','PUBLIC',


class TimeStampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now = True)
    
    class Meta:
        abstract = True
    
class Post(TimeStampModel):
    description = models.TextField()
    image = models.ImageField(upload_to='posts',blank = True,null = True)
    status = models.CharField(max_length = 100,choices=Status.choices,default=Status.DRAFT)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,blank = True,null=True)
    
    def __str__(self):
        return str(self.id)
    
    @property
    def likes_count(self):
        return self.likes.filter(is_liked = True).count()
    
    # class Meta:
    #     ordering = ['-created_at',]
    
class Comment(TimeStampModel):
    description = models.CharField(max_length=255)
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name = 'comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,blank = True,null=True)
    
    def __str__(self):
        return str(self.id)
    
class Like(TimeStampModel):
    is_liked = models.BooleanField(default=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,blank = True,null=True)
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name = 'likes')
    def __str__(self):
        return str(self.id)

post/forms.py
from django import forms
from post.models import Post,Comment

# class PostForm(forms.Form):
#     description=forms.CharField(widget=forms.Textarea)
#     image = forms.ImageField(widget=forms.ClearableFileInput,required=False)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('description','image','status')
        # exclude = ('user',)
        
    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            
    def clean_description(self):
        description = self.cleaned_data.get('description')
        if description.isnumeric():
            raise forms.ValidationError('post can not be number')
        return description
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("description",)
        

post/views.py
from django.shortcuts import render,reverse,get_object_or_404
from post.models import Post,Status,Like
from post.forms import PostForm,CommentForm
from django.http import HttpResponseRedirect,JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail


def home(request):
    posts = Post.objects.filter(status=Status.PUBLIC).order_by("-created_at")
    context = {'posts':posts}
    return render(request,'home.html',context)

@login_required
def create_post(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.user = request.user
        obj.save()
        messages.add_message(request,messages.INFO,'your post created successfully!')
        return HttpResponseRedirect(reverse('post:home'))
    context = {'form':form}
    return render(request,"post.html",context)

@login_required
def edit_post(request,postid):
    # try:
    #     post = Post.objects.get(id=postid)
    # except Post.DoesNotExist:
    #     raise Http404()
    post = get_object_or_404(Post,id=postid,user=request.user)
    form = PostForm(request.POST or None,instance=post)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.user = request.user
        obj.save()
        messages.add_message(request,messages.INFO,'your post updated sucessfully!')
        return HttpResponseRedirect(reverse('post:home'))
    context = {'form':form}
    return render(request,'post.html',context)

@login_required
def delete_post(request):
    postid = request.POST.get('postid')
    post = get_object_or_404(Post,id = postid,user=request.user)
    post.delete()
    messages.add_message(request,messages.INFO,'your post removed successfull')
    return HttpResponseRedirect(reverse('post:home'))

@login_required
def like_post(request,postid):
    post = get_object_or_404(Post,id = postid)
    user = request.user
    like,created = Like.objects.get_or_create(post = post,user = user)
    if not created:
        if like.is_liked:
            like.is_liked = False
        else:
            like.is_liked = True
        like.save()
    total = send_mail("post liked",f"your post: {post.description} has been likes.","prakashkchaudhary5209@gmail.com",[user.email])
    print(total)
    total_likes = post.likes.filter(is_liked = True).count()
    return JsonResponse({"likes":total_likes},safe = False)

@login_required
def comment_post(request,postid):
    post = get_object_or_404(Post,id = postid)
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.user = request.user
        comment.save()
        return HttpResponseRedirect(reverse('post:comment_post', args = (postid,)))
    context = {'post':post,'comments':comments,'form':form}
    return render(request,'post_comments.html',context)

post/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="row mt-3">
    <div class="col-sm-12 col-md-4 col-lg-4"></div>
    <div class="col-sm-12 col-md-4 col-lg-4">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
        {% if request.user.is_authenticated %}
            <h3>welcome {{ request.user.username }}</h3>
        {% endif %}
        <a class="btn btn-primary" href="{% url 'post:create_post' %}">Create your own Post</a>
        {% for post in posts %}
        <div class="card shadow mt-2 mb-2">
            <div class="card-body">
                    <p>{{post.description}}</p>
                    {% if post.image %}
                    <a target="_blank" href="{{post.image.url}}">
                        <img style="max-height:10em;" class="img-fluid" src='{{ post.image.url }}' alt=''/>    
                    </a>
                    {% endif %}
            </div>
            <div class="card-footer">
                <span>
                    <span id="like_count_{{post.id}}">{{post.likes_count}}</span>
                    <a class="like_post" id = "{{post.id}}" href="{% url 'post:like_post' post.id %}"><i class="bi bi-hand-thumbs-up"></i></a>
                    {% comment %} <a class="like-post" id="{{post.id}}" href="{% url 'post:like_post' post.id %}"><i class="bi bi-hand-thumbs-up"></i></a> {% endcomment %}
                </span>
                <span>{{post.comments.count}}</span>
                    <a href="{% url 'post:comment_post' post.id %}"><i class="bi bi-chat-left-text"></i></a>
                {% if request.user == post.user %}
                <div class="float-end">
                    <a class="text-decoration-none" href="{% url 'post:edit_post' post.id %}">Edit</a>
                    <a class="text-decoration-none text-danger" href="#" data-postid="{{post.id}}" data-bs-toggle="modal" data-bs-target="#exampleModal">delete</a>
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-sm-12 col-md-4 col-lg-4"></div>
</div>

  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Post</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">Are you sure you want to delete this post ?
            <form id="del-form" method="post" action="{% url 'post:delete_post' %}">
                {% csrf_token %}
                <input id="_postid" type="hidden" name="postid" />
            </form>
        </div> 
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button id="del-btn" type="button" class="btn btn-danger">Yes</button>
        </div>
      </div>
    </div>
  </div>
  
{% endblock content %}

{% block script %}
{{ block.super }}
<script type="text/javascript">
    $(document).ready(function(){
        
        let modal = document.getElementById("exampleModal");
        modal.addEventListener("show.bs.modal",function(evt){
            let deleteButton = evt.relatedTarget;
            $("#_postid").val(deleteButton.dataset.postid);
        });
        $("#del-btn").click(function(){
            $('#del-form').submit();
        })
     

        $(".like_post").click(function(evt){
            evt.preventDefault();
            let postid = evt.currentTarget.id;
            let url = evt.currentTarget.href;
            $.ajax({
                'url': url,
                'method': 'GET',
                'dataType': 'json',
                success:function(res){
                    $("#like_count_" + postid).html(res.likes);
                },
                error:function(res){
                    console.log(res);
                }
            })
        });
    });
</script>
{% endblock %}

post/templates/post.html
{% extends 'base.html' %}
{% block content %}
<div class="mt-5">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="text text-danger">
                {{ field.errors }}
            </div>
            {{ field.label_tag }}
            {{ field }}
        {% endfor %}
        <input class="btn btn-info" type="submit" name="submit" value="Create Post"/>
    </form>
</div>
{% endblock %}  

post/templates/post_comments.html
{% extends 'base.html' %}
{% block content %}
<div class = "row">
    <div class="col-sm-12 col-md-6 col-lg-6 border">
        <p>{{ post.description }}</p>
            {% if post.image %}
                <img class='img-fluid' src="{{ post.image.url }}" alt = "" />
            {% endif %}
    </div>
    <div class="col-sm-12 col-md-6 col-lg-6">
        <div class="border" style="max-height:300px; min-height:300px; overflow-y:scroll; border">
            {% for comment in comments %}
                <small><a class="text-decoration" href="{% url 'user:profile' comment.user.username %}">{{ comment.user.username }}</a></small>
                <p>{{ comment.description }}</p>
            {% endfor %}
        </div>
        <div class="border">
            <form method='post' action = "">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-primary" type="submit" name="submit" value="Comment"/>
            </form>
        </div>
    </div>
</div>
{% endblock content %}