chat/urls.py
from django.urls import path
from chat.views import message_view,message_to_user,delete_message

app_name = "chat"
urlpatterns = [
    path('messages/',message_view,name="messages"),
    path('messages/<str:username>/',message_to_user,name="message_user"),
    path('delete-message/',delete_message,name="delete_message"),
]

twitter/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls', namespace='post')),
    path('user/',include('useraccount.urls',namespace='user')),
    path('chat/',include('chat.urls',namespace='chat')),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from django.conf import settings
from post.models import TimeStampModel

class Message(TimeStampModel):
    description = models.TextField()
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name = "sent_messages")
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name = "received_messages")
    
    def __str__(self):
        return str(self.id)
    
    

chat/forms.py
from django import forms
from chat.models import Message

class ChatForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ("description",)

chat/views.py
from django.shortcuts import render,reverse,get_object_or_404
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from chat.models import Message
from chat.forms import ChatForm
from django.http import HttpResponseRedirect

User = get_user_model()

def message_view(request):
    users = User.objects.filter(is_superuser = False).exclude(id = request.user.id)
    context = {'users':users}
    return render(request,"message.html",context)

@login_required
def message_to_user(request,username):
    users = User.objects.filter(is_superuser = False).exclude(id = request.user.id)
    to_user = User.objects.get(username=username)
    messages = Message.objects.filter(
        from_user__in= [request.user,to_user], 
        to_user__in = [request.user,to_user],
        ).order_by('created_at')
    form = ChatForm(request.POST or None)
    if form.is_valid():
        message = form.save(commit=False)
        message.from_user = request.user
        message.to_user = to_user
        message.save()
        return HttpResponseRedirect(reverse('chat:message_user',args = (username, )))
    context = {"conversations":messages,"form":form,"users":users,"username":username}
    return render(request,"message.html",context) 

def delete_message(request):
    messageid = request.POST.get("messageid")
    message = get_object_or_404(Message,id=messageid,from_user = request.user)
    username = message.to_user.username
    message.delete()
    messages.add_message(request,messages.INFO,"your message is been deleted successfully")
    return HttpResponseRedirect(reverse("chat:message_user",args=(username,)))

chat/templates/message.html
{% extends 'base.html' %}
{% block content %}
<div class="row mt-3">
    <div class="col-sm-2 col-md-4 col-lg-4">
        {% comment %} {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %} {% endcomment %}
        <div class="border">
            <h3>Users</h3>
            {% for user in users %}
                <div>
                    <a class="{% if user.username != username %}text-decoration-none{% endif %}" href="{% url 'chat:message_user' user.username %}">{{ user.username }}</a>
                </div><br>
            {% endfor %}
        </div>
    </div>
    <div class="col-sm-10 col-md-8 col-lg-8">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success">
                {{message}}
            </div>
            {% endfor %}
        {% endif %} 
        <div style="max-height:300px; min-height:300px; overflow-y:scroll" class="border">
            {% for chat in conversations %}
                {% if chat.from_user == request.user %}
                    <div class="float-end">
                        <a class="text-decoration-none text-danger" data-messageid="{{chat.id}}" data-bs-toggle="modal" data-bs-target="#exampleModal" href="">
                            <small>Delete</small>
                        </a>
                        <span> {{ chat.description }}</span>
                    </div>
                {% else %}
                    <div class="">
                        <span> {{ chat.description }}</span>
                    </div>
                {% endif %}
                <br>
            {% endfor %}
        </div>
        <div class="border">
            <form method="post" action="">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" name="submit" value="send"/>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Message</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">Are you sure you want to delete this post ?
            <form id="del-form" method="post" action="{% url 'chat:delete_message' %}">
                {% csrf_token %}
                <input id="_messageid" type="hidden" name="messageid" />
            </form>
        </div> 
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button id="del-btn" type="button" class="btn btn-danger">Yes</button>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}


{% block script %}
{{ block.super }}
<script type="text/javascript">
    $(document).ready(function(){
        let modal = document.getElementById("exampleModal");
        modal.addEventListener("show.bs.modal",function(evt){
            let deleteButton = evt.relatedTarget;
            $("#_messageid").val(deleteButton.dataset.messageid);
        });
        $("#del-btn").click(function(){
            $('#del-form').submit();
        })
    }); 
</script>
{% endblock %}