chat/urls.py
from django.urls import path
from chat.views import message_view,message_to_user,delete_message

app_name = "chat"
urlpatterns = [
    path('messages/',message_view,name="messages"),
    path('messages/<str:username>/',message_to_user,name="message_user"),
    path('delete-message/',delete_message,name="delete_message"),
]

post/urls.py
from django.urls import path
from post.views import home,create_post,edit_post,delete_post,comment_post,like_post

app_name = 'post'
urlpatterns = [
    path('',home,name='home'),
    path('create-post/',create_post,name="create_post"),
    path('edit-post/<int:postid>/',edit_post,name="edit_post"),
    path('delete-post/',delete_post,name='delete_post'),
    path('like-post/<int:postid>/',like_post,name="like_post"),
    path('comment-post/<int:postid>/',comment_post,name="comment_post"),
]

twitter/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls', namespace='post')),
    path('user/',include('useraccount.urls',namespace='user')),
    path('chat/',include('chat.urls',namespace='chat')),
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

useraccount/urls.py
from django.urls import path
from useraccount.views import user_login,user_logout,UserLoginView,SignupView,profile_view,profile_update_view

app_name='user'
urlpatterns = [
    path('login/',user_login,name="login"),
    path('logout/',user_logout,name='logout'),
    path('register/',SignupView.as_view(),name='register'),
    path('profile/<str:username>/',profile_view, name='profile'),
    path('profile-edit/',profile_update_view,name="profile_update"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Twitter</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block stylesheet %}
            <link  rel = "stylesheet" href="{% static 'css/bs.min.css' %}" type = "text/css" />
            <link  rel = "stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css"/>
        {% endblock stylesheet %}
    </head>
    <body>
        <div class="container">
            {% block navbar %}
                {% include 'navbar.html' %}
            {% endblock navbar%}
            {% block content %}
            {% endblock content %}
        </div>
        {% block script %}
            <script src="{% static 'js/jquery.min.js' %}" type='text/javascript'></script>
            <script src="{% static 'js/bs.min.js' %}" type='text/javascript'></script>
        {% endblock script %}
    </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'post:home' %}">Twitter</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="{% url 'post:home' %}">Tweets</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:profile' request.user.username %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'chat:messages' %}">Messages</a>
          </li>
          {% endif %}
          {% if not request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:login' %}">Login</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:register' %}">sign up</a>
          </li>
          {% endif %}
          
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:logout' %}">logout</a>
          </li>
          {% endif %}


        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
</nav>